### ISSUE TITLE
不知道怎样导入数据库 平台导入限制30M

### ISSUE THREAD

**Issue by aa875982361** [huangjianke/weapp-poem#1]

**Comment by nslogx** [comment]
LeanCloud限制30M这个只能通过人为拆分数据来解决了

**Comment by luffykou** [comment]
@aa875982361 你好，你有拆分好小于30M的数据库吗？

@huangjianke 你好，能把你导入LeanCloud的数据库分享给我吗？

**Comment by ghostcode** [comment]
> LeanCloud限制30M这个只能通过人为拆分数据来解决了

导入MySql 的数据，LeanCloud 貌似不支持直接查询，怎么解决的？
