### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by cryzlasm** [huangjianke/weapp-poem#2]
建议(个人意见): 
1. 增加随机诗词, 增加喜爱收藏 (目前好像摘录只会显示那几句)
2. 解锁界面的复制功能, (有些繁体字真的不认识, 无法复制在其他地方查询, 或接入说文解字和简繁词典?)

**Comment by nslogx** [comment]
感谢建议！
1、下一步会增加搜索、收藏功能
2、计划下个版本增加简体字版本

**Comment by cryzlasm** [comment]
首先需要感谢您的无私奉献, 我个人是想学习繁体字, 但是有的繁体字不认识, 需要查, 是这个情况

**Comment by cryzlasm** [comment]
还有, 随机功能不知道会不会增加呢? 比如每天看的都是不一样的诗词随机展示

**Comment by nslogx** [comment]
明白你的意思了，有了新版本会通知您

**Comment by cryzlasm** [comment]
再次感谢您百忙之中响应一个偏远地区用户的小建议, 谢谢
